name: Generate Snake

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # não é necessário se você não estiver usando um repositório privado
          # para um repo privado, escreva seu nome de usuário/slug de repositório
          # Exemplo: Platane/snk => Platane/snk-private
          output: dist/snake.svg

      - uses: actions/upload-artifact@v2
        with:
          name: snake.svg
          path: dist/snake.svg
